/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package u.oop.project;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abelq
 */
public class UOopProject extends javax.swing.JFrame {

    /**
     * Creates new form NewJTestFrame
     */
    public UOopProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addClientejDialog = new javax.swing.JDialog();
        addClienteCorreoInput = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        addClienteIdInput = new javax.swing.JTextField();
        addClienteTipoDocInput = new javax.swing.JTextField();
        addClienteNumDocInput = new javax.swing.JTextField();
        addClienteNombreInput = new javax.swing.JTextField();
        addClienteSexoInput = new javax.swing.JTextField();
        addClienteEdadInput = new javax.swing.JTextField();
        addClienteCelularInput = new javax.swing.JTextField();
        addClienteButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        comprobantejDialog = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        comprobanteTotalLabel = new javax.swing.JLabel();
        comprobanteIdLabel = new javax.swing.JLabel();
        comprobanteTipoLabel = new javax.swing.JLabel();
        comprobanteFechaLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        comprobanteMozosTable = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        comprobanteProductosTable = new javax.swing.JTable();
        setMeseroToTablejDialog = new javax.swing.JDialog();
        meserobutton = new javax.swing.JButton();
        meseroSelect = new javax.swing.JComboBox<>();
        addMeserojDialog = new javax.swing.JDialog();
        addTrabajadorSueldoInput1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        addTrabajadorIdInput1 = new javax.swing.JTextField();
        addTrabajadorTipoDocInput1 = new javax.swing.JTextField();
        addTrabajadorNumDocInput1 = new javax.swing.JTextField();
        addTrabajadorNombreInput1 = new javax.swing.JTextField();
        addTrabajadorSexoInput1 = new javax.swing.JTextField();
        addTrabajadorEdadInput1 = new javax.swing.JTextField();
        addTrabajadorCelularInput1 = new javax.swing.JTextField();
        addTrabajadorFormButton = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        addTrabajadorCargoInput2 = new javax.swing.JTextField();
        addComidajDialog = new javax.swing.JDialog();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        addComidaIdInput2 = new javax.swing.JTextField();
        addComidaNombreInput2 = new javax.swing.JTextField();
        addComidaTemperaturaInput2 = new javax.swing.JTextField();
        addComidaFormButton1 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        addComidaTipoSelect = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        addComidaPrecioInput3 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        addComidaSaborInput3 = new javax.swing.JTextField();
        setComidajDialog = new javax.swing.JDialog();
        setComidaFormButton = new javax.swing.JButton();
        comidaComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        ClientTable3 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        tablaMozo3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaComida3 = new javax.swing.JTable();
        jButton15 = new javax.swing.JButton();
        pedirFacturaButton3 = new javax.swing.JButton();
        pedirBoletaButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        ClientTable1 = new javax.swing.JTable();
        jScrollPane13 = new javax.swing.JScrollPane();
        tablaMozo1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaComida1 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        pedirBoletaButton1 = new javax.swing.JButton();
        pedirFacturaButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        ClientTable2 = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        tablaMozo2 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaComida2 = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        pedirFacturaButton2 = new javax.swing.JButton();
        pedirBoletaButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        addClientejDialog.setTitle("AÑADE A UN CLIENTE");
        addClientejDialog.setMinimumSize(new java.awt.Dimension(315, 482));
        addClientejDialog.getContentPane().setLayout(null);

        addClienteCorreoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClienteCorreoInputActionPerformed(evt);
            }
        });
        addClientejDialog.getContentPane().add(addClienteCorreoInput);
        addClienteCorreoInput.setBounds(130, 330, 140, 19);

        jLabel16.setText("ID");
        addClientejDialog.getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 50, 60, 20);

        jLabel17.setText("TIPO DE DOC");
        addClientejDialog.getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 90, 80, 20);

        jLabel18.setText("NÚM DE DOC");
        addClientejDialog.getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 130, 90, 20);

        jLabel19.setText("NOMBRE");
        addClientejDialog.getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 170, 60, 20);

        jLabel20.setText("SEXO");
        addClientejDialog.getContentPane().add(jLabel20);
        jLabel20.setBounds(30, 210, 60, 20);

        jLabel21.setText("EDAD");
        addClientejDialog.getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 250, 60, 20);

        jLabel22.setText("CELULAR");
        addClientejDialog.getContentPane().add(jLabel22);
        jLabel22.setBounds(30, 290, 60, 20);

        jLabel23.setText("CORREO");
        addClientejDialog.getContentPane().add(jLabel23);
        jLabel23.setBounds(30, 330, 60, 20);

        addClienteIdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClienteIdInputActionPerformed(evt);
            }
        });
        addClientejDialog.getContentPane().add(addClienteIdInput);
        addClienteIdInput.setBounds(130, 50, 140, 19);

        addClienteTipoDocInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClienteTipoDocInputActionPerformed(evt);
            }
        });
        addClientejDialog.getContentPane().add(addClienteTipoDocInput);
        addClienteTipoDocInput.setBounds(130, 90, 140, 19);

        addClienteNumDocInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClienteNumDocInputActionPerformed(evt);
            }
        });
        addClientejDialog.getContentPane().add(addClienteNumDocInput);
        addClienteNumDocInput.setBounds(130, 130, 140, 19);

        addClienteNombreInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClienteNombreInputActionPerformed(evt);
            }
        });
        addClientejDialog.getContentPane().add(addClienteNombreInput);
        addClienteNombreInput.setBounds(130, 170, 140, 19);

        addClienteSexoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClienteSexoInputActionPerformed(evt);
            }
        });
        addClientejDialog.getContentPane().add(addClienteSexoInput);
        addClienteSexoInput.setBounds(130, 210, 140, 19);

        addClienteEdadInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClienteEdadInputActionPerformed(evt);
            }
        });
        addClientejDialog.getContentPane().add(addClienteEdadInput);
        addClienteEdadInput.setBounds(130, 250, 140, 19);

        addClienteCelularInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClienteCelularInputActionPerformed(evt);
            }
        });
        addClientejDialog.getContentPane().add(addClienteCelularInput);
        addClienteCelularInput.setBounds(130, 290, 140, 19);

        addClienteButton.setText("AÑADIR");
        addClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClienteButtonActionPerformed(evt);
            }
        });
        addClientejDialog.getContentPane().add(addClienteButton);
        addClienteButton.setBounds(100, 370, 81, 25);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("AÑADIR CLIENTE");
        addClientejDialog.getContentPane().add(jLabel14);
        jLabel14.setBounds(90, 20, 130, 19);

        comprobantejDialog.setTitle("AÑADE UN PRODUCTO");
        comprobantejDialog.setMinimumSize(new java.awt.Dimension(315, 482));
        comprobantejDialog.getContentPane().setLayout(null);

        jLabel15.setText("TOTAL A PAGAR");
        comprobantejDialog.getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 380, 110, 15);

        jLabel34.setText("ID DEL COMPROBANTE");
        comprobantejDialog.getContentPane().add(jLabel34);
        jLabel34.setBounds(40, 60, 140, 15);

        jLabel35.setText("TIPO DEL COMPROBANTE");
        comprobantejDialog.getContentPane().add(jLabel35);
        jLabel35.setBounds(40, 90, 150, 15);

        jLabel37.setText("FECHA");
        comprobantejDialog.getContentPane().add(jLabel37);
        jLabel37.setBounds(40, 120, 140, 15);

        jLabel38.setText("PLATOS Y BEBIDAS");
        comprobantejDialog.getContentPane().add(jLabel38);
        jLabel38.setBounds(40, 150, 140, 15);

        jLabel44.setText("MOZOS");
        comprobantejDialog.getContentPane().add(jLabel44);
        jLabel44.setBounds(40, 260, 140, 15);

        comprobanteTotalLabel.setText("TOTAL");
        comprobantejDialog.getContentPane().add(comprobanteTotalLabel);
        comprobanteTotalLabel.setBounds(230, 380, 40, 15);

        comprobanteIdLabel.setText("ID");
        comprobantejDialog.getContentPane().add(comprobanteIdLabel);
        comprobanteIdLabel.setBounds(230, 60, 270, 15);

        comprobanteTipoLabel.setText("TIPO");
        comprobantejDialog.getContentPane().add(comprobanteTipoLabel);
        comprobanteTipoLabel.setBounds(230, 90, 200, 15);

        comprobanteFechaLabel.setText("FECHA");
        comprobantejDialog.getContentPane().add(comprobanteFechaLabel);
        comprobanteFechaLabel.setBounds(230, 120, 270, 15);

        comprobanteMozosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "SABOR", "TEMP"
            }
        ));
        jScrollPane7.setViewportView(comprobanteMozosTable);

        comprobantejDialog.getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(230, 150, 310, 80);

        comprobanteProductosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO DOC", "NÚM DOC", "NOMBRE", "SEXO", "EDAD", "CELULAR", "CARGO", "SUELDO"
            }
        ));
        comprobanteProductosTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane15.setViewportView(comprobanteProductosTable);

        comprobantejDialog.getContentPane().add(jScrollPane15);
        jScrollPane15.setBounds(230, 260, 310, 100);

        setMeseroToTablejDialog.setTitle("AÑADE A UN MESERO");
        setMeseroToTablejDialog.setMinimumSize(new java.awt.Dimension(315, 482));
        setMeseroToTablejDialog.getContentPane().setLayout(null);

        meserobutton.setText("ASIGNAR");
        meserobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meserobuttonActionPerformed(evt);
            }
        });
        setMeseroToTablejDialog.getContentPane().add(meserobutton);
        meserobutton.setBounds(50, 120, 81, 25);

        meseroSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alberto Fujimori", "Alan Garcia", "Rafael Lopez" }));
        meseroSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meseroSelectActionPerformed(evt);
            }
        });
        setMeseroToTablejDialog.getContentPane().add(meseroSelect);
        meseroSelect.setBounds(20, 60, 150, 24);

        addMeserojDialog.setTitle("AÑADE A UN MESERO");
        addMeserojDialog.setMinimumSize(new java.awt.Dimension(315, 482));
        addMeserojDialog.getContentPane().setLayout(null);

        addTrabajadorSueldoInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrabajadorSueldoInput1ActionPerformed(evt);
            }
        });
        addMeserojDialog.getContentPane().add(addTrabajadorSueldoInput1);
        addTrabajadorSueldoInput1.setBounds(130, 270, 140, 19);

        jLabel24.setText("ID");
        addMeserojDialog.getContentPane().add(jLabel24);
        jLabel24.setBounds(30, 30, 60, 20);

        jLabel25.setText("TIPO DE DOC");
        addMeserojDialog.getContentPane().add(jLabel25);
        jLabel25.setBounds(30, 60, 80, 20);

        jLabel26.setText("NÚM DE DOC");
        addMeserojDialog.getContentPane().add(jLabel26);
        jLabel26.setBounds(30, 90, 90, 20);

        jLabel27.setText("NOMBRE");
        addMeserojDialog.getContentPane().add(jLabel27);
        jLabel27.setBounds(30, 120, 60, 20);

        jLabel28.setText("SEXO");
        addMeserojDialog.getContentPane().add(jLabel28);
        jLabel28.setBounds(30, 150, 60, 20);

        jLabel29.setText("EDAD");
        addMeserojDialog.getContentPane().add(jLabel29);
        jLabel29.setBounds(30, 180, 60, 20);

        jLabel30.setText("CELULAR");
        addMeserojDialog.getContentPane().add(jLabel30);
        jLabel30.setBounds(30, 210, 60, 20);

        jLabel31.setText("SUELDO");
        addMeserojDialog.getContentPane().add(jLabel31);
        jLabel31.setBounds(30, 270, 60, 20);

        addTrabajadorIdInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrabajadorIdInput1ActionPerformed(evt);
            }
        });
        addMeserojDialog.getContentPane().add(addTrabajadorIdInput1);
        addTrabajadorIdInput1.setBounds(130, 30, 140, 19);

        addTrabajadorTipoDocInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrabajadorTipoDocInput1ActionPerformed(evt);
            }
        });
        addMeserojDialog.getContentPane().add(addTrabajadorTipoDocInput1);
        addTrabajadorTipoDocInput1.setBounds(130, 60, 140, 19);

        addTrabajadorNumDocInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrabajadorNumDocInput1ActionPerformed(evt);
            }
        });
        addMeserojDialog.getContentPane().add(addTrabajadorNumDocInput1);
        addTrabajadorNumDocInput1.setBounds(130, 90, 140, 19);

        addTrabajadorNombreInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrabajadorNombreInput1ActionPerformed(evt);
            }
        });
        addMeserojDialog.getContentPane().add(addTrabajadorNombreInput1);
        addTrabajadorNombreInput1.setBounds(130, 120, 140, 19);

        addTrabajadorSexoInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrabajadorSexoInput1ActionPerformed(evt);
            }
        });
        addMeserojDialog.getContentPane().add(addTrabajadorSexoInput1);
        addTrabajadorSexoInput1.setBounds(130, 150, 140, 19);

        addTrabajadorEdadInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrabajadorEdadInput1ActionPerformed(evt);
            }
        });
        addMeserojDialog.getContentPane().add(addTrabajadorEdadInput1);
        addTrabajadorEdadInput1.setBounds(130, 180, 140, 19);

        addTrabajadorCelularInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrabajadorCelularInput1ActionPerformed(evt);
            }
        });
        addMeserojDialog.getContentPane().add(addTrabajadorCelularInput1);
        addTrabajadorCelularInput1.setBounds(130, 210, 140, 19);

        addTrabajadorFormButton.setText("AÑADIR");
        addTrabajadorFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrabajadorFormButtonActionPerformed(evt);
            }
        });
        addMeserojDialog.getContentPane().add(addTrabajadorFormButton);
        addTrabajadorFormButton.setBounds(100, 310, 81, 25);

        jLabel32.setText("CARGO");
        addMeserojDialog.getContentPane().add(jLabel32);
        jLabel32.setBounds(30, 240, 60, 20);

        addTrabajadorCargoInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrabajadorCargoInput2ActionPerformed(evt);
            }
        });
        addMeserojDialog.getContentPane().add(addTrabajadorCargoInput2);
        addTrabajadorCargoInput2.setBounds(130, 240, 140, 19);

        addComidajDialog.setTitle("AÑADE A UN MESERO");
        addComidajDialog.setMinimumSize(new java.awt.Dimension(315, 482));
        addComidajDialog.getContentPane().setLayout(null);

        jLabel33.setText("ID");
        addComidajDialog.getContentPane().add(jLabel33);
        jLabel33.setBounds(30, 30, 60, 20);

        jLabel36.setText("NOMBRE");
        addComidajDialog.getContentPane().add(jLabel36);
        jLabel36.setBounds(30, 60, 60, 20);

        jLabel40.setText("TEMPERATURA");
        addComidajDialog.getContentPane().add(jLabel40);
        jLabel40.setBounds(30, 190, 90, 20);

        addComidaIdInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComidaIdInput2ActionPerformed(evt);
            }
        });
        addComidajDialog.getContentPane().add(addComidaIdInput2);
        addComidaIdInput2.setBounds(130, 30, 140, 19);

        addComidaNombreInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComidaNombreInput2ActionPerformed(evt);
            }
        });
        addComidajDialog.getContentPane().add(addComidaNombreInput2);
        addComidaNombreInput2.setBounds(130, 60, 140, 19);

        addComidaTemperaturaInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComidaTemperaturaInput2ActionPerformed(evt);
            }
        });
        addComidajDialog.getContentPane().add(addComidaTemperaturaInput2);
        addComidaTemperaturaInput2.setBounds(130, 190, 140, 19);

        addComidaFormButton1.setText("AÑADIR");
        addComidaFormButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComidaFormButton1ActionPerformed(evt);
            }
        });
        addComidajDialog.getContentPane().add(addComidaFormButton1);
        addComidaFormButton1.setBounds(90, 230, 81, 25);

        jLabel41.setText("PRECIO");
        addComidajDialog.getContentPane().add(jLabel41);
        jLabel41.setBounds(30, 90, 60, 20);

        addComidaTipoSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plato", "Bebida" }));
        addComidajDialog.getContentPane().add(addComidaTipoSelect);
        addComidaTipoSelect.setBounds(130, 120, 140, 24);

        jLabel42.setText("TIPO");
        addComidajDialog.getContentPane().add(jLabel42);
        jLabel42.setBounds(30, 120, 60, 20);

        addComidaPrecioInput3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComidaPrecioInput3ActionPerformed(evt);
            }
        });
        addComidajDialog.getContentPane().add(addComidaPrecioInput3);
        addComidaPrecioInput3.setBounds(130, 90, 140, 19);

        jLabel43.setText("SABOR");
        addComidajDialog.getContentPane().add(jLabel43);
        jLabel43.setBounds(30, 160, 60, 20);

        addComidaSaborInput3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComidaSaborInput3ActionPerformed(evt);
            }
        });
        addComidajDialog.getContentPane().add(addComidaSaborInput3);
        addComidaSaborInput3.setBounds(130, 160, 140, 19);

        setComidajDialog.setTitle("AÑADE UN PRODUCTO");
        setComidajDialog.setMinimumSize(new java.awt.Dimension(315, 482));
        setComidajDialog.getContentPane().setLayout(null);

        setComidaFormButton.setText("PEDIR");
        setComidaFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setComidaFormButtonActionPerformed(evt);
            }
        });
        setComidajDialog.getContentPane().add(setComidaFormButton);
        setComidaFormButton.setBounds(50, 120, 81, 25);

        comidaComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1/4 pollo", "1/2 pollo", "1 pollo", "3lt Inkacola", "1.5lt Inkacola" }));
        comidaComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comidaComboBox1ActionPerformed(evt);
            }
        });
        setComidajDialog.getContentPane().add(comidaComboBox1);
        comidaComboBox1.setBounds(20, 60, 150, 24);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(null);

        jLabel1.setText("Happy Chicken");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 10, 150, 30);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MESA 3");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 20, 60, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PEDIDO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 350, 50, 20);

        jButton1.setText("AÑADIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(233, 350, 90, 25);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CLIENTE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 50, 50, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MOZO");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 200, 50, 20);

        jButton3.setText("ASIGNAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(223, 200, 100, 25);

        ClientTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO DOC", "NÚM DOC", "NOMBRE", "SEXO", "EDAD", "CELULAR", "CORREO"
            }
        ));
        ClientTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane5.setViewportView(ClientTable3);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(10, 80, 310, 100);

        tablaMozo3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO DOC", "NÚM DOC", "NOMBRE", "SEXO", "EDAD", "CELULAR", "CARGO", "SUELDO"
            }
        ));
        tablaMozo3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane10.setViewportView(tablaMozo3);

        jPanel1.add(jScrollPane10);
        jScrollPane10.setBounds(10, 230, 310, 100);

        tablaComida3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO", "NOMBRE", "PRECIO", "SABOR", "TEMP"
            }
        ));
        jScrollPane4.setViewportView(tablaComida3);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(10, 390, 310, 100);

        jButton15.setText("AÑADIR");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(223, 50, 100, 25);

        pedirFacturaButton3.setText("PEDIR FACTURA");
        pedirFacturaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirFacturaButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(pedirFacturaButton3);
        pedirFacturaButton3.setBounds(150, 510, 170, 25);

        pedirBoletaButton3.setText("PEDIR BOLETA");
        pedirBoletaButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirBoletaButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(pedirBoletaButton3);
        pedirBoletaButton3.setBounds(10, 510, 120, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(720, 50, 350, 560);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MESA 1");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(150, 20, 60, 20);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PEDIDO");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 350, 50, 20);

        jButton4.setText("AÑADIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(243, 350, 90, 25);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CLIENTE");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 50, 50, 20);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MOZO");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 200, 50, 20);

        jButton6.setText("ASIGNAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(233, 200, 100, 25);

        ClientTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO DOC", "NÚM DOC", "NOMBRE", "SEXO", "EDAD", "CELULAR", "CORREO"
            }
        ));
        ClientTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane12.setViewportView(ClientTable1);

        jPanel2.add(jScrollPane12);
        jScrollPane12.setBounds(20, 80, 310, 100);

        tablaMozo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO DOC", "NÚM DOC", "NOMBRE", "SEXO", "EDAD", "CELULAR", "CARGO", "SUELDO"
            }
        ));
        tablaMozo1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane13.setViewportView(tablaMozo1);

        jPanel2.add(jScrollPane13);
        jScrollPane13.setBounds(20, 230, 310, 100);

        tablaComida1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "PRECIO", "SABOR", "TEMP"
            }
        ));
        jScrollPane6.setViewportView(tablaComida1);

        jPanel2.add(jScrollPane6);
        jScrollPane6.setBounds(20, 390, 310, 100);

        jButton13.setText("AÑADIR");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13);
        jButton13.setBounds(243, 50, 90, 25);

        pedirBoletaButton1.setText("PEDIR BOLETA");
        pedirBoletaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirBoletaButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(pedirBoletaButton1);
        pedirBoletaButton1.setBounds(20, 510, 120, 25);

        pedirFacturaButton1.setText("PEDIR FACTURA");
        pedirFacturaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirFacturaButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(pedirFacturaButton1);
        pedirFacturaButton1.setBounds(160, 510, 170, 25);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 50, 350, 560);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MESA 2");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(150, 20, 60, 20);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PEDIDO");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 350, 50, 20);

        jButton7.setText("AÑADIR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(243, 350, 80, 25);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CLIENTE");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 50, 50, 20);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("MOZO");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 200, 50, 20);

        jButton9.setText("ASIGNAR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);
        jButton9.setBounds(223, 200, 100, 25);

        ClientTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO DOC", "NÚM DOC", "NOMBRE", "SEXO", "EDAD", "CELULAR", "CORREO"
            }
        ));
        ClientTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane11.setViewportView(ClientTable2);

        jPanel3.add(jScrollPane11);
        jScrollPane11.setBounds(20, 80, 310, 100);

        tablaMozo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO DOC", "NÚM DOC", "NOMBRE", "SEXO", "EDAD", "CELULAR", "CARGO", "SUELDO"
            }
        ));
        tablaMozo2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane14.setViewportView(tablaMozo2);

        jPanel3.add(jScrollPane14);
        jScrollPane14.setBounds(20, 230, 310, 100);

        tablaComida2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO", "NOMBRE", "PRECIO", "SABOR", "TEMP"
            }
        ));
        jScrollPane8.setViewportView(tablaComida2);

        jPanel3.add(jScrollPane8);
        jScrollPane8.setBounds(20, 390, 310, 100);

        jButton14.setText("AÑADIR");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton14);
        jButton14.setBounds(233, 50, 90, 25);

        pedirFacturaButton2.setText("PEDIR FACTURA");
        pedirFacturaButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirFacturaButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(pedirFacturaButton2);
        pedirFacturaButton2.setBounds(160, 510, 170, 25);

        pedirBoletaButton2.setText("PEDIR BOLETA");
        pedirBoletaButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirBoletaButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(pedirBoletaButton2);
        pedirBoletaButton2.setBounds(20, 510, 120, 25);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(370, 50, 340, 560);

        jButton5.setText("AÑADIR PLATO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(180, 10, 150, 25);

        jButton16.setText("AÑADIR MOZO");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(10, 10, 150, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.comprobantejDialog.setVisible(true);
        this.mesaADondeAñadirPlato = 3;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setMeseroToTablejDialog.setVisible(true);
        this.mesaADondeAñadirMozo = 3;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setComidajDialog.setVisible(true);
        this.mesaADondeAñadirPlato = 1;
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        this.addComidajDialog.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setMeseroToTablejDialog.setVisible(true);
        this.mesaADondeAñadirMozo = 1;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.comprobantejDialog.setVisible(true);
        this.mesaADondeAñadirPlato = 2;
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.setMeseroToTablejDialog.setVisible(true);
        this.mesaADondeAñadirMozo = 2;
    }//GEN-LAST:event_jButton9ActionPerformed

    private void addClienteCorreoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClienteCorreoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addClienteCorreoInputActionPerformed

    private void addClienteIdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClienteIdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addClienteIdInputActionPerformed

    private void addClienteTipoDocInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClienteTipoDocInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addClienteTipoDocInputActionPerformed

    private void addClienteNumDocInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClienteNumDocInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addClienteNumDocInputActionPerformed

    private void addClienteNombreInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClienteNombreInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addClienteNombreInputActionPerformed

    private void addClienteSexoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClienteSexoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addClienteSexoInputActionPerformed

    private void addClienteEdadInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClienteEdadInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addClienteEdadInputActionPerformed

    private void addClienteCelularInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClienteCelularInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addClienteCelularInputActionPerformed

    private void addClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClienteButtonActionPerformed
    
         
        try{
            int newClientId = Integer.parseInt(this.addClienteIdInput.getText());
            int newClientNumDoc = Integer.parseInt(this.addClienteNumDocInput.getText());
            int newClientEdad = Integer.parseInt(this.addClienteEdadInput.getText());
            int newClientCelular = Integer.parseInt(this.addClienteCelularInput.getText());
            
            // creando cliente
            Cliente newCliente = new Cliente(
          this.addClienteCorreoInput.getText(),
             newClientId,
        this.addClienteTipoDocInput.getText(),
       newClientNumDoc,
          this.addClienteNombreInput.getText(),
           this.addClienteSexoInput.getText(),
           newClientEdad,
         newClientCelular
            );
            
            // creando registro para la tabla
            String newClienteData[] = {
                this.addClienteIdInput.getText(),
                this.addClienteTipoDocInput.getText(),
                this.addClienteNumDocInput.getText(),
                this.addClienteNombreInput.getText(),
                this.addClienteSexoInput.getText(),
                this.addClienteEdadInput.getText(),
                this.addClienteCelularInput.getText(),
                this.addClienteCorreoInput.getText()
            };
            
            // creando variable para la tabla a seleccionada
            javax.swing.JTable selectedClientTable;
            Mesa selectedClientMesa;
            switch(this.mesaADondeAñadirCliente) {
                case 1 -> { selectedClientTable = this.ClientTable1; selectedClientMesa = mesa1; }
                case 2 -> { selectedClientTable = this.ClientTable2; selectedClientMesa = mesa2; }
                case 3 -> { selectedClientTable = this.ClientTable3; selectedClientMesa = mesa3; }
                default -> { selectedClientTable = this.ClientTable1; selectedClientMesa = mesa1; }
            }
            
            // añadiendo cliente al registro de la mesa
            selectedClientMesa.getListaClientes().add(newCliente);
            
            // añadiendo row a la tabla
            DefaultTableModel clientTableModel = (DefaultTableModel)selectedClientTable.getModel();
            clientTableModel.addRow(newClienteData);
            
            // ocultando modal
            this.addClientejDialog.setVisible(false);
            
        }catch (NumberFormatException e){
            System.out.println(e);
            System.out.println("falló la creación del new cliente");
        }
    }//GEN-LAST:event_addClienteButtonActionPerformed

    private void meserobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meserobuttonActionPerformed
       
        System.out.print(this.meseroSelect.getSelectedItem());
        
        javax.swing.JTable selectedMozoTable;
        Mesa selectedMozoMesa;
        
        switch(this.mesaADondeAñadirMozo) {
            case 1 -> { selectedMozoTable = this.tablaMozo1; }
            case 2 -> { selectedMozoTable = this.tablaMozo2; }
            case 3 -> { selectedMozoTable = this.tablaMozo3; }
            default -> { selectedMozoTable = this.tablaMozo1; }
        }
        
        switch(this.mesaADondeAñadirMozo) {
            case 1 -> { selectedMozoMesa = mesa1 ; }
            case 2 -> { selectedMozoMesa = mesa2; }
            case 3 -> { selectedMozoMesa = mesa3; }
            default -> { selectedMozoMesa = mesa1; }
        }
        
        Trabajador trabajadorAAñadir = trabajadoressDisponibles.get(0);
        for (int i = 0; i < trabajadoressDisponibles.size(); i++ ){
            if(this.meseroSelect.getSelectedItem().equals(trabajadoressDisponibles.get(i).getNombre())){
                trabajadorAAñadir = trabajadoressDisponibles.get(i);
            }
        }
        
        selectedMozoMesa.getListaTrabajadores().add(trabajadorAAñadir);
        
        String mozoData[] = {
            String.valueOf(trabajadorAAñadir.getId()),
            trabajadorAAñadir.getTipo_doc(),
            String.valueOf(trabajadorAAñadir.getNumero_doc()),
            trabajadorAAñadir.getNombre(),
            trabajadorAAñadir.getSexo(),
            String.valueOf(trabajadorAAñadir.getEdad()),
            String.valueOf(trabajadorAAñadir.getCelular()), 
            trabajadorAAñadir.getCargo(),
            String.valueOf(trabajadorAAñadir.getSueldo())
        };
        
        // añadiendo row a la tabla
        DefaultTableModel clientTableModel = (DefaultTableModel)selectedMozoTable.getModel();
        clientTableModel.addRow(mozoData);
        
        //this.meserobutton.getText()
        this.setMeseroToTablejDialog.setVisible(false);
        
    }//GEN-LAST:event_meserobuttonActionPerformed

    private void meseroSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meseroSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meseroSelectActionPerformed

    private void addTrabajadorSueldoInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrabajadorSueldoInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTrabajadorSueldoInput1ActionPerformed

    private void addTrabajadorIdInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrabajadorIdInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTrabajadorIdInput1ActionPerformed

    private void addTrabajadorTipoDocInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrabajadorTipoDocInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTrabajadorTipoDocInput1ActionPerformed

    private void addTrabajadorNumDocInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrabajadorNumDocInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTrabajadorNumDocInput1ActionPerformed

    private void addTrabajadorNombreInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrabajadorNombreInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTrabajadorNombreInput1ActionPerformed

    private void addTrabajadorSexoInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrabajadorSexoInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTrabajadorSexoInput1ActionPerformed

    private void addTrabajadorEdadInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrabajadorEdadInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTrabajadorEdadInput1ActionPerformed

    private void addTrabajadorCelularInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrabajadorCelularInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTrabajadorCelularInput1ActionPerformed

    private void addTrabajadorFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrabajadorFormButtonActionPerformed
        
        try{
            int newTrabajadorId = Integer.parseInt(this.addTrabajadorIdInput1.getText());
            int newTrabajadorNumDoc = Integer.parseInt(this.addTrabajadorNumDocInput1.getText());
            int newTrabajadorEdad = Integer.parseInt(this.addTrabajadorEdadInput1.getText());
            int newTrabajadorCelular = Integer.parseInt(this.addTrabajadorCelularInput1.getText());
            int newTrabajadorSueldo = Integer.parseInt(this.addTrabajadorSueldoInput1.getText());
            
            // creando Trabajador
            Trabajador newTrabajador = new Trabajador(
                this.addTrabajadorCargoInput2.getText(),
                newTrabajadorSueldo,
                newTrabajadorId,
                this.addTrabajadorTipoDocInput1.getText(),
                newTrabajadorNumDoc,
                this.addTrabajadorNombreInput1.getText(),
                this.addTrabajadorSexoInput1.getText(),
                newTrabajadorEdad,
                newTrabajadorCelular
            );
            
            // añadiendo cliente a su vector
            this.trabajadoressDisponibles.add(newTrabajador);
            
            this.meseroSelect.addItem(newTrabajador.getNombre());
            
            this.addMeserojDialog.setVisible(false);
            
        }catch (NumberFormatException e){
            System.out.println("falló la creación del new trabajador");
        }
        
    }//GEN-LAST:event_addTrabajadorFormButtonActionPerformed

    private void addTrabajadorCargoInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrabajadorCargoInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTrabajadorCargoInput2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        this.addClientejDialog.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        this.addMeserojDialog.setVisible(true);
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void addComidaIdInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComidaIdInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addComidaIdInput2ActionPerformed

    private void addComidaNombreInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComidaNombreInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addComidaNombreInput2ActionPerformed

    private void addComidaTemperaturaInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComidaTemperaturaInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addComidaTemperaturaInput2ActionPerformed

    private void addComidaFormButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComidaFormButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
            int newComidaId = Integer.parseInt(this.addComidaIdInput2 .getText());
            int newComidaPrecio = Integer.parseInt(this.addComidaPrecioInput3.getText());
            
            if(this.addComidaTipoSelect.getSelectedItem().equals("Plato")){
                Plato newPlato = new Plato(
                    this.addComidaSaborInput3 .getText(),
                    newComidaId,
                    this.addComidaNombreInput2.getText(),
                    newComidaPrecio
                );
                
                PlatosDisponibles.add(newPlato);

                this.comidaComboBox1.addItem(newPlato.getNombre());

                this.addComidajDialog.setVisible(false);
                
            }else{
                Bebida newBebida = new Bebida(
                    this.addComidaTemperaturaInput2.getText(),
                    newComidaId,
                    this.addComidaNombreInput2.getText(),
                    newComidaPrecio
                );
                
                // añadiendo bebida a su vector
                bebidasDisponibles.add(newBebida);

                this.comidaComboBox1.addItem(newBebida.getNombre());

                this.addComidajDialog.setVisible(false);
            }
            

            
        }catch (NumberFormatException e){
            System.out.println("falló la creación del new trabajador");
        }
        
    }//GEN-LAST:event_addComidaFormButton1ActionPerformed

    private void addComidaPrecioInput3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComidaPrecioInput3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addComidaPrecioInput3ActionPerformed

    private void addComidaSaborInput3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComidaSaborInput3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addComidaSaborInput3ActionPerformed

    private void pedirFacturaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirFacturaButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pedirFacturaButton3ActionPerformed

    private void pedirBoletaButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirBoletaButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pedirBoletaButton3ActionPerformed

    private void pedirBoletaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirBoletaButton1ActionPerformed
        // TODO add your handling code here:
        Comprobante nuevoComprobante = new Comprobante(
                1,
                "boleta",
                new Date(),
                mesa1
        );
        
        this.comprobanteIdLabel.setText(Integer.toString(nuevoComprobante.getMesa().getId()));
        this.comprobanteTipoLabel.setText(nuevoComprobante.getTipo());
        
        String pattern = "MM/dd/yyyy HH:mm:ss";

        
        DateFormat df = new SimpleDateFormat(pattern);
        
        this.comprobanteFechaLabel.setText(df.format(nuevoComprobante.getFecha()));
        
        for(int i = 0; i < nuevoComprobante.getMesa().getListaTrabajadores().size() ; i++){
            
            String mozoData[] = {
                String.valueOf(nuevoComprobante.getMesa().getListaTrabajadores().get(i).getId()),
                nuevoComprobante.getMesa().getListaTrabajadores().get(i).getTipo_doc(),
                String.valueOf(nuevoComprobante.getMesa().getListaTrabajadores().get(i).getNumero_doc()),
                nuevoComprobante.getMesa().getListaTrabajadores().get(i).getNombre(),
                nuevoComprobante.getMesa().getListaTrabajadores().get(i).getSexo(),
                String.valueOf(nuevoComprobante.getMesa().getListaTrabajadores().get(i).getEdad()),
                String.valueOf(nuevoComprobante.getMesa().getListaTrabajadores().get(i).getCelular()), 
                nuevoComprobante.getMesa().getListaTrabajadores().get(i).getCargo(),
                String.valueOf(nuevoComprobante.getMesa().getListaTrabajadores().get(i).getSueldo())
            };
        
            // añadiendo row a la tabla
            DefaultTableModel comprobanteMozosTableModel = (DefaultTableModel) this.comprobanteMozosTable.getModel();
            comprobanteMozosTableModel.addRow(mozoData);
            
        }
        
        for(int i = 0; i < nuevoComprobante.getMesa().getListaPlatos().size(); i++){
            
            String platoData[] = {
                String.valueOf(nuevoComprobante.getMesa().getListaPlatos().get(i).getId()),
                nuevoComprobante.getMesa().getListaPlatos().get(i).getNombre(),
                String.valueOf(nuevoComprobante.getMesa().getListaPlatos().get(i).getPrecio()),
                nuevoComprobante.getMesa().getListaPlatos().get(i).getSabor(),
                "----"
            };
        
            // añadiendo row a la tabla
            DefaultTableModel comprobanteMozosTableModel = (DefaultTableModel) this.comprobanteProductosTable.getModel();
            comprobanteMozosTableModel.addRow(platoData);
            
        }
        
        for(int i = 0; i < nuevoComprobante.getMesa().getListaBebidas().size(); i++){
            
            String bebidaData[] = {
                    String.valueOf(nuevoComprobante.getMesa().getListaBebidas().get(i).getId()),
                    nuevoComprobante.getMesa().getListaBebidas().get(i).getNombre(),
                    String.valueOf(nuevoComprobante.getMesa().getListaBebidas().get(i).getPrecio()),
                    "----",
                    nuevoComprobante.getMesa().getListaBebidas().get(i).getTemperatura(),
            };
        
            // añadiendo row a la tabla
            DefaultTableModel comprobanteMozosTableModel = (DefaultTableModel) this.comprobanteProductosTable.getModel();
            comprobanteMozosTableModel.addRow(bebidaData);
            
        }
        
        
        //this.comprobanteTotalLabel;
        
        this.comprobantejDialog.setVisible(true);
    }//GEN-LAST:event_pedirBoletaButton1ActionPerformed

    private void pedirFacturaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirFacturaButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pedirFacturaButton1ActionPerformed

    private void pedirFacturaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirFacturaButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pedirFacturaButton2ActionPerformed

    private void pedirBoletaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirBoletaButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pedirBoletaButton2ActionPerformed

    private void setComidaFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setComidaFormButtonActionPerformed
        // TODO add your handling code here:
        
        System.out.print(this.meseroSelect.getSelectedItem());
        
        javax.swing.JTable selectedPlatoTable;
        Mesa selectedPlatoMesa;
        
        switch(this.mesaADondeAñadirPlato) {
            case 1 -> { selectedPlatoTable = this.tablaComida1 ; }
            case 2 -> { selectedPlatoTable = this.tablaComida2; }
            case 3 -> { selectedPlatoTable = this.tablaComida3; }
            default -> { selectedPlatoTable = this.tablaComida1; }
        }
        
        switch(this.mesaADondeAñadirPlato) {
            case 1 -> { selectedPlatoMesa = mesa1 ; }
            case 2 -> { selectedPlatoMesa = mesa2; }
            case 3 -> { selectedPlatoMesa = mesa3; }
            default -> { selectedPlatoMesa = mesa1; }
        }
        
        for (int i = 0; i < PlatosDisponibles.size(); i++ ){
            if(this.comidaComboBox1.getSelectedItem().equals(PlatosDisponibles.get(i).getNombre())){
            
                selectedPlatoMesa.getListaPlatos().add(PlatosDisponibles.get(i));

                String platoData[] = {
                    String.valueOf(PlatosDisponibles.get(i).getId()),
                    PlatosDisponibles.get(i).getNombre(),
                    String.valueOf(PlatosDisponibles.get(i).getPrecio()),
                    PlatosDisponibles.get(i).getSabor(),
                    "----"
                };

                // añadiendo row a la tabla
                DefaultTableModel platoTableModel = (DefaultTableModel) selectedPlatoTable.getModel();
                platoTableModel.addRow(platoData);
            }
        }
        
        for (int i = 0; i < bebidasDisponibles.size(); i++ ){
            if(this.comidaComboBox1.getSelectedItem().equals(bebidasDisponibles.get(i).getNombre())){
            
                selectedPlatoMesa.getListaBebidas().add(bebidasDisponibles.get(i));

                String bebidaData[] = {
                    String.valueOf(bebidasDisponibles.get(i).getId()),
                    bebidasDisponibles.get(i).getNombre(),
                    String.valueOf(bebidasDisponibles.get(i).getPrecio()),
                    "----",
                    bebidasDisponibles.get(i).getTemperatura(),
                };

                // añadiendo row a la tabla
                DefaultTableModel bebidaTableModel = (DefaultTableModel) selectedPlatoTable.getModel();
                bebidaTableModel.addRow(bebidaData);
            }
        }
        
        //this.meserobutton.getText()
        this.setMeseroToTablejDialog.setVisible(false);
    }//GEN-LAST:event_setComidaFormButtonActionPerformed

    private void comidaComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comidaComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comidaComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UOopProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UOopProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UOopProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UOopProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UOopProject().setVisible(true);
            }
        });
        
        // añadiendo los productos disponibles a su vector
        
        PlatosDisponibles.add(platoDisponible1);
        PlatosDisponibles.add(platoDisponible2);
        PlatosDisponibles.add(platoDisponible3);
        
        bebidasDisponibles.add(bebidaDisponible1);
        bebidasDisponibles.add(bebidaDisponible2);
        
        //productosDisponibles.add(bebidaDisponible1);
        //productosDisponibles.add(bebidaDisponible2);
        
        // añadiendo los trabajadores disponibles a su vector
        
        trabajadoressDisponibles.add(trabajadorDisponible1);
        trabajadoressDisponibles.add(trabajadorDisponible2);
        trabajadoressDisponibles.add(trabajadorDisponible3);
    }
    
    // MESA 1
    static Vector<Cliente> ClientesMesa1 = new Vector();
    static Vector<Trabajador>  TrabajadoresMesa1 = new Vector();
    static Vector<Plato>  platosMesa1 = new Vector();
    static Vector<Bebida>  bebidassMesa1 = new Vector();
    static Mesa mesa1 = new Mesa(
            1,
            1,
            ClientesMesa1,
            TrabajadoresMesa1,
            platosMesa1,
            bebidassMesa1
    );
    
    // MESA 2
    static Vector<Cliente> ClientesMesa2 = new Vector();
    static Vector<Trabajador>  TrabajadoresMesa2 = new Vector();
    static Vector<Plato>  platosMesa2 = new Vector();
    static Vector<Bebida>  bebidassMesa2 = new Vector();
    static Mesa mesa2 = new Mesa(
            2,
            2,
            ClientesMesa2,
            TrabajadoresMesa2,
            platosMesa2,
            bebidassMesa2
    );
    
    // MESA 3
    static Vector<Cliente> ClientesMesa3 = new Vector();
    static Vector<Trabajador>  TrabajadoresMesa3 = new Vector();
    static Vector<Plato>  platosMesa3 = new Vector();
    static Vector<Bebida>  bebidassMesa3 = new Vector();
    static Mesa mesa3 = new Mesa(
            3,
            3,
            ClientesMesa3,
            TrabajadoresMesa3,
            platosMesa3,
            bebidassMesa3
    );
    
    // GENERALES
    private int mesaADondeAñadirCliente;
    private int mesaADondeAñadirMozo;
    private int mesaADondeAñadirPlato;
    
    // trabajadores disponibles
    static Trabajador trabajadorDisponible1 = new Trabajador("Mozo", 1000, 1, "dni", 74356037, "Alberto Fujimori", "M", 20, 987918828);
    static Trabajador trabajadorDisponible2 = new Trabajador("Mozo", 1000, 1, "dni", 35654037, "Alan Garcia", "M", 25, 937914228);
    static Trabajador trabajadorDisponible3 = new Trabajador("Mozo", 1000, 1, "dni", 11654037, "Rafael Lopez", "M", 25, 457914228);
    
    private static Vector<Trabajador> trabajadoressDisponibles = new Vector();
    
    // productos disponibles
    static Plato platoDisponible1 = new Plato("salado", 1, "1/4 pollo", 15);
    static Plato platoDisponible2 = new Plato("salado", 1, "1/2 pollo", 30);
    static Plato platoDisponible3 = new Plato("salado", 1, "1 pollo", 45);
    static Bebida bebidaDisponible1 = new Bebida("frio", 1, "3lt Inkacola", 10);
    static Bebida bebidaDisponible2 = new Bebida("frio", 1, "1.5lt Inkacola", 5);
    
    private static Vector<Plato> PlatosDisponibles = new Vector();
    private static Vector<Bebida> bebidasDisponibles = new Vector();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientTable1;
    private javax.swing.JTable ClientTable2;
    private javax.swing.JTable ClientTable3;
    private javax.swing.JButton addClienteButton;
    private javax.swing.JTextField addClienteCelularInput;
    private javax.swing.JTextField addClienteCorreoInput;
    private javax.swing.JTextField addClienteEdadInput;
    private javax.swing.JTextField addClienteIdInput;
    private javax.swing.JTextField addClienteNombreInput;
    private javax.swing.JTextField addClienteNumDocInput;
    private javax.swing.JTextField addClienteSexoInput;
    private javax.swing.JTextField addClienteTipoDocInput;
    private javax.swing.JDialog addClientejDialog;
    private javax.swing.JButton addComidaFormButton1;
    private javax.swing.JTextField addComidaIdInput2;
    private javax.swing.JTextField addComidaNombreInput2;
    private javax.swing.JTextField addComidaPrecioInput3;
    private javax.swing.JTextField addComidaSaborInput3;
    private javax.swing.JTextField addComidaTemperaturaInput2;
    private javax.swing.JComboBox<String> addComidaTipoSelect;
    private javax.swing.JDialog addComidajDialog;
    private javax.swing.JDialog addMeserojDialog;
    private javax.swing.JTextField addTrabajadorCargoInput2;
    private javax.swing.JTextField addTrabajadorCelularInput1;
    private javax.swing.JTextField addTrabajadorEdadInput1;
    private javax.swing.JButton addTrabajadorFormButton;
    private javax.swing.JTextField addTrabajadorIdInput1;
    private javax.swing.JTextField addTrabajadorNombreInput1;
    private javax.swing.JTextField addTrabajadorNumDocInput1;
    private javax.swing.JTextField addTrabajadorSexoInput1;
    private javax.swing.JTextField addTrabajadorSueldoInput1;
    private javax.swing.JTextField addTrabajadorTipoDocInput1;
    private javax.swing.JComboBox<String> comidaComboBox1;
    private javax.swing.JLabel comprobanteFechaLabel;
    private javax.swing.JLabel comprobanteIdLabel;
    private javax.swing.JTable comprobanteMozosTable;
    private javax.swing.JTable comprobanteProductosTable;
    private javax.swing.JLabel comprobanteTipoLabel;
    private javax.swing.JLabel comprobanteTotalLabel;
    private javax.swing.JDialog comprobantejDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JComboBox<String> meseroSelect;
    private javax.swing.JButton meserobutton;
    private javax.swing.JButton pedirBoletaButton1;
    private javax.swing.JButton pedirBoletaButton2;
    private javax.swing.JButton pedirBoletaButton3;
    private javax.swing.JButton pedirFacturaButton1;
    private javax.swing.JButton pedirFacturaButton2;
    private javax.swing.JButton pedirFacturaButton3;
    private javax.swing.JButton setComidaFormButton;
    private javax.swing.JDialog setComidajDialog;
    private javax.swing.JDialog setMeseroToTablejDialog;
    private javax.swing.JTable tablaComida1;
    private javax.swing.JTable tablaComida2;
    private javax.swing.JTable tablaComida3;
    private javax.swing.JTable tablaMozo1;
    private javax.swing.JTable tablaMozo2;
    private javax.swing.JTable tablaMozo3;
    // End of variables declaration//GEN-END:variables
}
